version: "3.8"
services:
  db:
    image: postgres:14.5
    container_name: postgres14
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fpbank

  fp-user-service:
    image: fp-user-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fp-user-service
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
