spring:
  application:
    name: fp-user

  #  use db as datasource service name for generate image
  datasource:
    url: jdbc:postgresql://localhost:5432/fpbank?currentSchema=bank_schema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        format_sql: true

