spring:
  application:
    name: fp-user

  #  use db as datasource service name for generate image
  datasource:
    url: jdbc:postgresql://db:5432/fpbank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        format_sql: true
    show-sql: true
    generate-ddl: true

